### PR TITLE
Fixed Equality operator bug

### LINKED ISSUE #32: Audit: BidContract Equality operator use instead of Assignment Operator
Double equality sign has been used instead of single equality sign(i.e. assignment operator). Doing so would result in the value of that 
variable to be the same as before leading to unintended results such as withdrawing the amount again even though it had already been withdrawn.

### PR DESCRIPTION
**Pull request by vishaldantuluri**
Closes #32

### CODE REVIEW

**Review by parva-jain — APPROVED** [review]
Looks good. Also, there are more equality operator bugs like this in other contracts. They will be covered in further issues and PRs? @vishaldantuluri

**Review by kishan79 — APPROVED** [review]
@vishaldantuluri  Changes verified.

**Comment by kishan79** [comment]
> Looks good. Also, there are more equality operator bugs like this in other contracts. They will be covered in further issues and PRs? @vishaldantuluri

@parva-jain Yes, other similar bugs in different contract while be fixed in their respective assigned issues.

**Comment by vishaldantuluri** [comment]
@parva-jain can you make issues for wherever these bugs are present.

**Pull request merged**
