### PR TITLE
Wrap call response in require function

### PR DESCRIPTION
**Pull request by kishan79**

### CODE REVIEW

**Comment by parva-jain** [comment]
@kishan79 Isn't that increasing contract size?? What's the need for this change??

**Comment by kishan79** [comment]
@parva-jain Yeah, it will add on to the contract size, this was added to avoid unexpected results

**Comment by sanskarkhare** [comment]
Can we use Reentrancy guard of openzepplin in the functions instead of these wrappers.

**Review by parva-jain — APPROVED** [review]
verified the changes and ran tests as well

**Pull request merged**
